/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranslateIndexRouteImport } from './routes/translate/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TranslatePricingRouteImport } from './routes/translate/pricing'
import { Route as TranslateLiveRouteImport } from './routes/translate/live'
import { Route as TranslateLanguagesRouteImport } from './routes/translate/languages'
import { Route as TranslateHowItWorksRouteImport } from './routes/translate/how-it-works'
import { Route as TranslateDocumentRouteImport } from './routes/translate/document'
import { Route as SignupVerifyEmailRouteImport } from './routes/signup.verify-email'
import { Route as ServicesVisaRouteImport } from './routes/services.visa'
import { Route as ServicesTranslationRouteImport } from './routes/services.translation'
import { Route as ServicesConsultancyRouteImport } from './routes/services.consultancy'
import { Route as ServicesAccountingRouteImport } from './routes/services.accounting'
import { Route as Login2faRouteImport } from './routes/login.2fa'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard.services.index'
import { Route as DashboardMyServicesIndexRouteImport } from './routes/dashboard.my-services.index'
import { Route as DashboardClaimsIndexRouteImport } from './routes/dashboard.claims.index'
import { Route as DashboardServicesSlugRouteImport } from './routes/dashboard.services.$slug'
import { Route as DashboardMyServicesIdRouteImport } from './routes/dashboard.my-services.$id'
import { Route as DashboardClaimsNewRouteImport } from './routes/dashboard.claims.new'
import { Route as DashboardClaimsIdRouteImport } from './routes/dashboard.claims.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateIndexRoute = TranslateIndexRouteImport.update({
  id: '/translate/',
  path: '/translate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TranslatePricingRoute = TranslatePricingRouteImport.update({
  id: '/translate/pricing',
  path: '/translate/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateLiveRoute = TranslateLiveRouteImport.update({
  id: '/translate/live',
  path: '/translate/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateLanguagesRoute = TranslateLanguagesRouteImport.update({
  id: '/translate/languages',
  path: '/translate/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateHowItWorksRoute = TranslateHowItWorksRouteImport.update({
  id: '/translate/how-it-works',
  path: '/translate/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateDocumentRoute = TranslateDocumentRouteImport.update({
  id: '/translate/document',
  path: '/translate/document',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyEmailRoute = SignupVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => SignupRoute,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/services/visa',
  path: '/services/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTranslationRoute = ServicesTranslationRouteImport.update({
  id: '/services/translation',
  path: '/services/translation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsultancyRoute = ServicesConsultancyRouteImport.update({
  id: '/services/consultancy',
  path: '/services/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccountingRoute = ServicesAccountingRouteImport.update({
  id: '/services/accounting',
  path: '/services/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const Login2faRoute = Login2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyServicesIndexRoute =
  DashboardMyServicesIndexRouteImport.update({
    id: '/my-services/',
    path: '/my-services/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClaimsIndexRoute = DashboardClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesSlugRoute = DashboardServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyServicesIdRoute = DashboardMyServicesIdRouteImport.update({
  id: '/my-services/$id',
  path: '/my-services/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsNewRoute = DashboardClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsIdRoute = DashboardClaimsIdRouteImport.update({
  id: '/claims/$id',
  path: '/claims/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dev': typeof DevRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/login/2fa': typeof Login2faRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/consultancy': typeof ServicesConsultancyRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/visa': typeof ServicesVisaRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/translate/document': typeof TranslateDocumentRoute
  '/translate/how-it-works': typeof TranslateHowItWorksRoute
  '/translate/languages': typeof TranslateLanguagesRoute
  '/translate/live': typeof TranslateLiveRoute
  '/translate/pricing': typeof TranslatePricingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/translate/': typeof TranslateIndexRoute
  '/dashboard/claims/$id': typeof DashboardClaimsIdRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
  '/dashboard/my-services/$id': typeof DashboardMyServicesIdRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugRoute
  '/dashboard/claims/': typeof DashboardClaimsIndexRoute
  '/dashboard/my-services/': typeof DashboardMyServicesIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dev': typeof DevRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/login/2fa': typeof Login2faRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/consultancy': typeof ServicesConsultancyRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/visa': typeof ServicesVisaRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/translate/document': typeof TranslateDocumentRoute
  '/translate/how-it-works': typeof TranslateHowItWorksRoute
  '/translate/languages': typeof TranslateLanguagesRoute
  '/translate/live': typeof TranslateLiveRoute
  '/translate/pricing': typeof TranslatePricingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
  '/translate': typeof TranslateIndexRoute
  '/dashboard/claims/$id': typeof DashboardClaimsIdRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
  '/dashboard/my-services/$id': typeof DashboardMyServicesIdRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugRoute
  '/dashboard/claims': typeof DashboardClaimsIndexRoute
  '/dashboard/my-services': typeof DashboardMyServicesIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dev': typeof DevRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/login/2fa': typeof Login2faRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/consultancy': typeof ServicesConsultancyRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/visa': typeof ServicesVisaRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/translate/document': typeof TranslateDocumentRoute
  '/translate/how-it-works': typeof TranslateHowItWorksRoute
  '/translate/languages': typeof TranslateLanguagesRoute
  '/translate/live': typeof TranslateLiveRoute
  '/translate/pricing': typeof TranslatePricingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/translate/': typeof TranslateIndexRoute
  '/dashboard/claims/$id': typeof DashboardClaimsIdRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
  '/dashboard/my-services/$id': typeof DashboardMyServicesIdRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugRoute
  '/dashboard/claims/': typeof DashboardClaimsIndexRoute
  '/dashboard/my-services/': typeof DashboardMyServicesIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/dev'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/auth/error'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/login/2fa'
    | '/services/accounting'
    | '/services/consultancy'
    | '/services/translation'
    | '/services/visa'
    | '/signup/verify-email'
    | '/translate/document'
    | '/translate/how-it-works'
    | '/translate/languages'
    | '/translate/live'
    | '/translate/pricing'
    | '/dashboard/'
    | '/services/'
    | '/translate/'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/my-services/$id'
    | '/dashboard/services/$slug'
    | '/dashboard/claims/'
    | '/dashboard/my-services/'
    | '/dashboard/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dev'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/auth/error'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/login/2fa'
    | '/services/accounting'
    | '/services/consultancy'
    | '/services/translation'
    | '/services/visa'
    | '/signup/verify-email'
    | '/translate/document'
    | '/translate/how-it-works'
    | '/translate/languages'
    | '/translate/live'
    | '/translate/pricing'
    | '/dashboard'
    | '/services'
    | '/translate'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/my-services/$id'
    | '/dashboard/services/$slug'
    | '/dashboard/claims'
    | '/dashboard/my-services'
    | '/dashboard/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/dev'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/auth/error'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/login/2fa'
    | '/services/accounting'
    | '/services/consultancy'
    | '/services/translation'
    | '/services/visa'
    | '/signup/verify-email'
    | '/translate/document'
    | '/translate/how-it-works'
    | '/translate/languages'
    | '/translate/live'
    | '/translate/pricing'
    | '/dashboard/'
    | '/services/'
    | '/translate/'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/my-services/$id'
    | '/dashboard/services/$slug'
    | '/dashboard/claims/'
    | '/dashboard/my-services/'
    | '/dashboard/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevRoute: typeof DevRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  ServicesAccountingRoute: typeof ServicesAccountingRoute
  ServicesConsultancyRoute: typeof ServicesConsultancyRoute
  ServicesTranslationRoute: typeof ServicesTranslationRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  TranslateDocumentRoute: typeof TranslateDocumentRoute
  TranslateHowItWorksRoute: typeof TranslateHowItWorksRoute
  TranslateLanguagesRoute: typeof TranslateLanguagesRoute
  TranslateLiveRoute: typeof TranslateLiveRoute
  TranslatePricingRoute: typeof TranslatePricingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TranslateIndexRoute: typeof TranslateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/': {
      id: '/translate/'
      path: '/translate'
      fullPath: '/translate/'
      preLoaderRoute: typeof TranslateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/translate/pricing': {
      id: '/translate/pricing'
      path: '/translate/pricing'
      fullPath: '/translate/pricing'
      preLoaderRoute: typeof TranslatePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/live': {
      id: '/translate/live'
      path: '/translate/live'
      fullPath: '/translate/live'
      preLoaderRoute: typeof TranslateLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/languages': {
      id: '/translate/languages'
      path: '/translate/languages'
      fullPath: '/translate/languages'
      preLoaderRoute: typeof TranslateLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/how-it-works': {
      id: '/translate/how-it-works'
      path: '/translate/how-it-works'
      fullPath: '/translate/how-it-works'
      preLoaderRoute: typeof TranslateHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/document': {
      id: '/translate/document'
      path: '/translate/document'
      fullPath: '/translate/document'
      preLoaderRoute: typeof TranslateDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/verify-email': {
      id: '/signup/verify-email'
      path: '/verify-email'
      fullPath: '/signup/verify-email'
      preLoaderRoute: typeof SignupVerifyEmailRouteImport
      parentRoute: typeof SignupRoute
    }
    '/services/visa': {
      id: '/services/visa'
      path: '/services/visa'
      fullPath: '/services/visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/translation': {
      id: '/services/translation'
      path: '/services/translation'
      fullPath: '/services/translation'
      preLoaderRoute: typeof ServicesTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consultancy': {
      id: '/services/consultancy'
      path: '/services/consultancy'
      fullPath: '/services/consultancy'
      preLoaderRoute: typeof ServicesConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accounting': {
      id: '/services/accounting'
      path: '/services/accounting'
      fullPath: '/services/accounting'
      preLoaderRoute: typeof ServicesAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/2fa': {
      id: '/login/2fa'
      path: '/2fa'
      fullPath: '/login/2fa'
      preLoaderRoute: typeof Login2faRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services/'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-services/': {
      id: '/dashboard/my-services/'
      path: '/my-services'
      fullPath: '/dashboard/my-services/'
      preLoaderRoute: typeof DashboardMyServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/': {
      id: '/dashboard/claims/'
      path: '/claims'
      fullPath: '/dashboard/claims/'
      preLoaderRoute: typeof DashboardClaimsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug': {
      id: '/dashboard/services/$slug'
      path: '/services/$slug'
      fullPath: '/dashboard/services/$slug'
      preLoaderRoute: typeof DashboardServicesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-services/$id': {
      id: '/dashboard/my-services/$id'
      path: '/my-services/$id'
      fullPath: '/dashboard/my-services/$id'
      preLoaderRoute: typeof DashboardMyServicesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/new': {
      id: '/dashboard/claims/new'
      path: '/claims/new'
      fullPath: '/dashboard/claims/new'
      preLoaderRoute: typeof DashboardClaimsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/$id': {
      id: '/dashboard/claims/$id'
      path: '/claims/$id'
      fullPath: '/dashboard/claims/$id'
      preLoaderRoute: typeof DashboardClaimsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClaimsIdRoute: typeof DashboardClaimsIdRoute
  DashboardClaimsNewRoute: typeof DashboardClaimsNewRoute
  DashboardMyServicesIdRoute: typeof DashboardMyServicesIdRoute
  DashboardServicesSlugRoute: typeof DashboardServicesSlugRoute
  DashboardClaimsIndexRoute: typeof DashboardClaimsIndexRoute
  DashboardMyServicesIndexRoute: typeof DashboardMyServicesIndexRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClaimsIdRoute: DashboardClaimsIdRoute,
  DashboardClaimsNewRoute: DashboardClaimsNewRoute,
  DashboardMyServicesIdRoute: DashboardMyServicesIdRoute,
  DashboardServicesSlugRoute: DashboardServicesSlugRoute,
  DashboardClaimsIndexRoute: DashboardClaimsIndexRoute,
  DashboardMyServicesIndexRoute: DashboardMyServicesIndexRoute,
  DashboardServicesIndexRoute: DashboardServicesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LoginRouteChildren {
  Login2faRoute: typeof Login2faRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  Login2faRoute: Login2faRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupVerifyEmailRoute: typeof SignupVerifyEmailRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupVerifyEmailRoute: SignupVerifyEmailRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevRoute: DevRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  ServicesAccountingRoute: ServicesAccountingRoute,
  ServicesConsultancyRoute: ServicesConsultancyRoute,
  ServicesTranslationRoute: ServicesTranslationRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  TranslateDocumentRoute: TranslateDocumentRoute,
  TranslateHowItWorksRoute: TranslateHowItWorksRoute,
  TranslateLanguagesRoute: TranslateLanguagesRoute,
  TranslateLiveRoute: TranslateLiveRoute,
  TranslatePricingRoute: TranslatePricingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TranslateIndexRoute: TranslateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
