/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranslateIndexRouteImport } from './routes/translate/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TranslatePricingRouteImport } from './routes/translate/pricing'
import { Route as TranslateLiveRouteImport } from './routes/translate/live'
import { Route as TranslateLanguagesRouteImport } from './routes/translate/languages'
import { Route as TranslateHowItWorksRouteImport } from './routes/translate/how-it-works'
import { Route as TranslateDocumentRouteImport } from './routes/translate/document'
import { Route as StaffVisaRouteImport } from './routes/staff.visa'
import { Route as StaffTranslationRouteImport } from './routes/staff.translation'
import { Route as StaffSettingsRouteImport } from './routes/staff.settings'
import { Route as StaffReportsRouteImport } from './routes/staff.reports'
import { Route as StaffMessagesRouteImport } from './routes/staff.messages'
import { Route as StaffConsultancyRouteImport } from './routes/staff.consultancy'
import { Route as StaffAdminRouteImport } from './routes/staff.admin'
import { Route as StaffAccountingRouteImport } from './routes/staff.accounting'
import { Route as SignupVerifyEmailRouteImport } from './routes/signup.verify-email'
import { Route as ServicesVisaRouteImport } from './routes/services.visa'
import { Route as ServicesTranslationRouteImport } from './routes/services.translation'
import { Route as ServicesConsultancyRouteImport } from './routes/services.consultancy'
import { Route as ServicesAccountingRouteImport } from './routes/services.accounting'
import { Route as Login2faRouteImport } from './routes/login.2fa'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TranslateLiveIndexRouteImport } from './routes/translate/live/index'
import { Route as StaffVisaIndexRouteImport } from './routes/staff.visa.index'
import { Route as StaffTranslationIndexRouteImport } from './routes/staff.translation.index'
import { Route as StaffConsultancyIndexRouteImport } from './routes/staff.consultancy.index'
import { Route as StaffClientsIndexRouteImport } from './routes/staff.clients.index'
import { Route as StaffClaimsIndexRouteImport } from './routes/staff.claims.index'
import { Route as StaffAccountingIndexRouteImport } from './routes/staff.accounting.index'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard.services.index'
import { Route as DashboardMyServicesIndexRouteImport } from './routes/dashboard.my-services.index'
import { Route as DashboardClaimsIndexRouteImport } from './routes/dashboard.claims.index'
import { Route as TranslateLiveSessionRouteImport } from './routes/translate.live.session'
import { Route as StaffVisaIdRouteImport } from './routes/staff.visa.$id'
import { Route as StaffTranslationIdRouteImport } from './routes/staff.translation.$id'
import { Route as StaffConsultancyIdRouteImport } from './routes/staff.consultancy.$id'
import { Route as StaffClientsNewRouteImport } from './routes/staff.clients.new'
import { Route as StaffClientsIdRouteImport } from './routes/staff.clients.$id'
import { Route as StaffClaimsIdRouteImport } from './routes/staff.claims.$id'
import { Route as StaffAccountingIdRouteImport } from './routes/staff.accounting.$id'
import { Route as DashboardServicesSlugRouteImport } from './routes/dashboard.services.$slug'
import { Route as DashboardMyServicesIdRouteImport } from './routes/dashboard.my-services.$id'
import { Route as DashboardClaimsNewRouteImport } from './routes/dashboard.claims.new'
import { Route as DashboardClaimsIdRouteImport } from './routes/dashboard.claims.$id'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateIndexRoute = TranslateIndexRouteImport.update({
  id: '/translate/',
  path: '/translate/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TranslatePricingRoute = TranslatePricingRouteImport.update({
  id: '/translate/pricing',
  path: '/translate/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateLiveRoute = TranslateLiveRouteImport.update({
  id: '/translate/live',
  path: '/translate/live',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateLanguagesRoute = TranslateLanguagesRouteImport.update({
  id: '/translate/languages',
  path: '/translate/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateHowItWorksRoute = TranslateHowItWorksRouteImport.update({
  id: '/translate/how-it-works',
  path: '/translate/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateDocumentRoute = TranslateDocumentRouteImport.update({
  id: '/translate/document',
  path: '/translate/document',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffVisaRoute = StaffVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTranslationRoute = StaffTranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMessagesRoute = StaffMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConsultancyRoute = StaffConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAdminRoute = StaffAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAccountingRoute = StaffAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => StaffRoute,
} as any)
const SignupVerifyEmailRoute = SignupVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => SignupRoute,
} as any)
const ServicesVisaRoute = ServicesVisaRouteImport.update({
  id: '/services/visa',
  path: '/services/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTranslationRoute = ServicesTranslationRouteImport.update({
  id: '/services/translation',
  path: '/services/translation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsultancyRoute = ServicesConsultancyRouteImport.update({
  id: '/services/consultancy',
  path: '/services/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccountingRoute = ServicesAccountingRouteImport.update({
  id: '/services/accounting',
  path: '/services/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const Login2faRoute = Login2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateLiveIndexRoute = TranslateLiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TranslateLiveRoute,
} as any)
const StaffVisaIndexRoute = StaffVisaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffVisaRoute,
} as any)
const StaffTranslationIndexRoute = StaffTranslationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffTranslationRoute,
} as any)
const StaffConsultancyIndexRoute = StaffConsultancyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffConsultancyRoute,
} as any)
const StaffClientsIndexRoute = StaffClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClaimsIndexRoute = StaffClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAccountingIndexRoute = StaffAccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffAccountingRoute,
} as any)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyServicesIndexRoute =
  DashboardMyServicesIndexRouteImport.update({
    id: '/my-services/',
    path: '/my-services/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardClaimsIndexRoute = DashboardClaimsIndexRouteImport.update({
  id: '/claims/',
  path: '/claims/',
  getParentRoute: () => DashboardRoute,
} as any)
const TranslateLiveSessionRoute = TranslateLiveSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => TranslateLiveRoute,
} as any)
const StaffVisaIdRoute = StaffVisaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffVisaRoute,
} as any)
const StaffTranslationIdRoute = StaffTranslationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffTranslationRoute,
} as any)
const StaffConsultancyIdRoute = StaffConsultancyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffConsultancyRoute,
} as any)
const StaffClientsNewRoute = StaffClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClientsIdRoute = StaffClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClaimsIdRoute = StaffClaimsIdRouteImport.update({
  id: '/claims/$id',
  path: '/claims/$id',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAccountingIdRoute = StaffAccountingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffAccountingRoute,
} as any)
const DashboardServicesSlugRoute = DashboardServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyServicesIdRoute = DashboardMyServicesIdRouteImport.update({
  id: '/my-services/$id',
  path: '/my-services/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsNewRoute = DashboardClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsIdRoute = DashboardClaimsIdRouteImport.update({
  id: '/claims/$id',
  path: '/claims/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dev': typeof DevRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/login/2fa': typeof Login2faRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/consultancy': typeof ServicesConsultancyRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/visa': typeof ServicesVisaRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/staff/accounting': typeof StaffAccountingRouteWithChildren
  '/staff/admin': typeof StaffAdminRoute
  '/staff/consultancy': typeof StaffConsultancyRouteWithChildren
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/translation': typeof StaffTranslationRouteWithChildren
  '/staff/visa': typeof StaffVisaRouteWithChildren
  '/translate/document': typeof TranslateDocumentRoute
  '/translate/how-it-works': typeof TranslateHowItWorksRoute
  '/translate/languages': typeof TranslateLanguagesRoute
  '/translate/live': typeof TranslateLiveRouteWithChildren
  '/translate/pricing': typeof TranslatePricingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/translate/': typeof TranslateIndexRoute
  '/dashboard/claims/$id': typeof DashboardClaimsIdRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
  '/dashboard/my-services/$id': typeof DashboardMyServicesIdRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugRoute
  '/staff/accounting/$id': typeof StaffAccountingIdRoute
  '/staff/claims/$id': typeof StaffClaimsIdRoute
  '/staff/clients/$id': typeof StaffClientsIdRoute
  '/staff/clients/new': typeof StaffClientsNewRoute
  '/staff/consultancy/$id': typeof StaffConsultancyIdRoute
  '/staff/translation/$id': typeof StaffTranslationIdRoute
  '/staff/visa/$id': typeof StaffVisaIdRoute
  '/translate/live/session': typeof TranslateLiveSessionRoute
  '/dashboard/claims/': typeof DashboardClaimsIndexRoute
  '/dashboard/my-services/': typeof DashboardMyServicesIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/staff/accounting/': typeof StaffAccountingIndexRoute
  '/staff/claims/': typeof StaffClaimsIndexRoute
  '/staff/clients/': typeof StaffClientsIndexRoute
  '/staff/consultancy/': typeof StaffConsultancyIndexRoute
  '/staff/translation/': typeof StaffTranslationIndexRoute
  '/staff/visa/': typeof StaffVisaIndexRoute
  '/translate/live/': typeof TranslateLiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dev': typeof DevRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/login/2fa': typeof Login2faRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/consultancy': typeof ServicesConsultancyRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/visa': typeof ServicesVisaRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/staff/admin': typeof StaffAdminRoute
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/translate/document': typeof TranslateDocumentRoute
  '/translate/how-it-works': typeof TranslateHowItWorksRoute
  '/translate/languages': typeof TranslateLanguagesRoute
  '/translate/pricing': typeof TranslatePricingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
  '/staff': typeof StaffIndexRoute
  '/translate': typeof TranslateIndexRoute
  '/dashboard/claims/$id': typeof DashboardClaimsIdRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
  '/dashboard/my-services/$id': typeof DashboardMyServicesIdRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugRoute
  '/staff/accounting/$id': typeof StaffAccountingIdRoute
  '/staff/claims/$id': typeof StaffClaimsIdRoute
  '/staff/clients/$id': typeof StaffClientsIdRoute
  '/staff/clients/new': typeof StaffClientsNewRoute
  '/staff/consultancy/$id': typeof StaffConsultancyIdRoute
  '/staff/translation/$id': typeof StaffTranslationIdRoute
  '/staff/visa/$id': typeof StaffVisaIdRoute
  '/translate/live/session': typeof TranslateLiveSessionRoute
  '/dashboard/claims': typeof DashboardClaimsIndexRoute
  '/dashboard/my-services': typeof DashboardMyServicesIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/staff/accounting': typeof StaffAccountingIndexRoute
  '/staff/claims': typeof StaffClaimsIndexRoute
  '/staff/clients': typeof StaffClientsIndexRoute
  '/staff/consultancy': typeof StaffConsultancyIndexRoute
  '/staff/translation': typeof StaffTranslationIndexRoute
  '/staff/visa': typeof StaffVisaIndexRoute
  '/translate/live': typeof TranslateLiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dev': typeof DevRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/login/2fa': typeof Login2faRoute
  '/services/accounting': typeof ServicesAccountingRoute
  '/services/consultancy': typeof ServicesConsultancyRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/visa': typeof ServicesVisaRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/staff/accounting': typeof StaffAccountingRouteWithChildren
  '/staff/admin': typeof StaffAdminRoute
  '/staff/consultancy': typeof StaffConsultancyRouteWithChildren
  '/staff/messages': typeof StaffMessagesRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/translation': typeof StaffTranslationRouteWithChildren
  '/staff/visa': typeof StaffVisaRouteWithChildren
  '/translate/document': typeof TranslateDocumentRoute
  '/translate/how-it-works': typeof TranslateHowItWorksRoute
  '/translate/languages': typeof TranslateLanguagesRoute
  '/translate/live': typeof TranslateLiveRouteWithChildren
  '/translate/pricing': typeof TranslatePricingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/translate/': typeof TranslateIndexRoute
  '/dashboard/claims/$id': typeof DashboardClaimsIdRoute
  '/dashboard/claims/new': typeof DashboardClaimsNewRoute
  '/dashboard/my-services/$id': typeof DashboardMyServicesIdRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugRoute
  '/staff/accounting/$id': typeof StaffAccountingIdRoute
  '/staff/claims/$id': typeof StaffClaimsIdRoute
  '/staff/clients/$id': typeof StaffClientsIdRoute
  '/staff/clients/new': typeof StaffClientsNewRoute
  '/staff/consultancy/$id': typeof StaffConsultancyIdRoute
  '/staff/translation/$id': typeof StaffTranslationIdRoute
  '/staff/visa/$id': typeof StaffVisaIdRoute
  '/translate/live/session': typeof TranslateLiveSessionRoute
  '/dashboard/claims/': typeof DashboardClaimsIndexRoute
  '/dashboard/my-services/': typeof DashboardMyServicesIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/staff/accounting/': typeof StaffAccountingIndexRoute
  '/staff/claims/': typeof StaffClaimsIndexRoute
  '/staff/clients/': typeof StaffClientsIndexRoute
  '/staff/consultancy/': typeof StaffConsultancyIndexRoute
  '/staff/translation/': typeof StaffTranslationIndexRoute
  '/staff/visa/': typeof StaffVisaIndexRoute
  '/translate/live/': typeof TranslateLiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/dev'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/staff'
    | '/auth/callback'
    | '/auth/error'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/login/2fa'
    | '/services/accounting'
    | '/services/consultancy'
    | '/services/translation'
    | '/services/visa'
    | '/signup/verify-email'
    | '/staff/accounting'
    | '/staff/admin'
    | '/staff/consultancy'
    | '/staff/messages'
    | '/staff/reports'
    | '/staff/settings'
    | '/staff/translation'
    | '/staff/visa'
    | '/translate/document'
    | '/translate/how-it-works'
    | '/translate/languages'
    | '/translate/live'
    | '/translate/pricing'
    | '/dashboard/'
    | '/services/'
    | '/staff/'
    | '/translate/'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/my-services/$id'
    | '/dashboard/services/$slug'
    | '/staff/accounting/$id'
    | '/staff/claims/$id'
    | '/staff/clients/$id'
    | '/staff/clients/new'
    | '/staff/consultancy/$id'
    | '/staff/translation/$id'
    | '/staff/visa/$id'
    | '/translate/live/session'
    | '/dashboard/claims/'
    | '/dashboard/my-services/'
    | '/dashboard/services/'
    | '/staff/accounting/'
    | '/staff/claims/'
    | '/staff/clients/'
    | '/staff/consultancy/'
    | '/staff/translation/'
    | '/staff/visa/'
    | '/translate/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dev'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/auth/error'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/login/2fa'
    | '/services/accounting'
    | '/services/consultancy'
    | '/services/translation'
    | '/services/visa'
    | '/signup/verify-email'
    | '/staff/admin'
    | '/staff/messages'
    | '/staff/reports'
    | '/staff/settings'
    | '/translate/document'
    | '/translate/how-it-works'
    | '/translate/languages'
    | '/translate/pricing'
    | '/dashboard'
    | '/services'
    | '/staff'
    | '/translate'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/my-services/$id'
    | '/dashboard/services/$slug'
    | '/staff/accounting/$id'
    | '/staff/claims/$id'
    | '/staff/clients/$id'
    | '/staff/clients/new'
    | '/staff/consultancy/$id'
    | '/staff/translation/$id'
    | '/staff/visa/$id'
    | '/translate/live/session'
    | '/dashboard/claims'
    | '/dashboard/my-services'
    | '/dashboard/services'
    | '/staff/accounting'
    | '/staff/claims'
    | '/staff/clients'
    | '/staff/consultancy'
    | '/staff/translation'
    | '/staff/visa'
    | '/translate/live'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/dev'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/staff'
    | '/auth/callback'
    | '/auth/error'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/login/2fa'
    | '/services/accounting'
    | '/services/consultancy'
    | '/services/translation'
    | '/services/visa'
    | '/signup/verify-email'
    | '/staff/accounting'
    | '/staff/admin'
    | '/staff/consultancy'
    | '/staff/messages'
    | '/staff/reports'
    | '/staff/settings'
    | '/staff/translation'
    | '/staff/visa'
    | '/translate/document'
    | '/translate/how-it-works'
    | '/translate/languages'
    | '/translate/live'
    | '/translate/pricing'
    | '/dashboard/'
    | '/services/'
    | '/staff/'
    | '/translate/'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/my-services/$id'
    | '/dashboard/services/$slug'
    | '/staff/accounting/$id'
    | '/staff/claims/$id'
    | '/staff/clients/$id'
    | '/staff/clients/new'
    | '/staff/consultancy/$id'
    | '/staff/translation/$id'
    | '/staff/visa/$id'
    | '/translate/live/session'
    | '/dashboard/claims/'
    | '/dashboard/my-services/'
    | '/dashboard/services/'
    | '/staff/accounting/'
    | '/staff/claims/'
    | '/staff/clients/'
    | '/staff/consultancy/'
    | '/staff/translation/'
    | '/staff/visa/'
    | '/translate/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevRoute: typeof DevRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  ServicesAccountingRoute: typeof ServicesAccountingRoute
  ServicesConsultancyRoute: typeof ServicesConsultancyRoute
  ServicesTranslationRoute: typeof ServicesTranslationRoute
  ServicesVisaRoute: typeof ServicesVisaRoute
  TranslateDocumentRoute: typeof TranslateDocumentRoute
  TranslateHowItWorksRoute: typeof TranslateHowItWorksRoute
  TranslateLanguagesRoute: typeof TranslateLanguagesRoute
  TranslateLiveRoute: typeof TranslateLiveRouteWithChildren
  TranslatePricingRoute: typeof TranslatePricingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TranslateIndexRoute: typeof TranslateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/': {
      id: '/translate/'
      path: '/translate'
      fullPath: '/translate/'
      preLoaderRoute: typeof TranslateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/translate/pricing': {
      id: '/translate/pricing'
      path: '/translate/pricing'
      fullPath: '/translate/pricing'
      preLoaderRoute: typeof TranslatePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/live': {
      id: '/translate/live'
      path: '/translate/live'
      fullPath: '/translate/live'
      preLoaderRoute: typeof TranslateLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/languages': {
      id: '/translate/languages'
      path: '/translate/languages'
      fullPath: '/translate/languages'
      preLoaderRoute: typeof TranslateLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/how-it-works': {
      id: '/translate/how-it-works'
      path: '/translate/how-it-works'
      fullPath: '/translate/how-it-works'
      preLoaderRoute: typeof TranslateHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/document': {
      id: '/translate/document'
      path: '/translate/document'
      fullPath: '/translate/document'
      preLoaderRoute: typeof TranslateDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/visa': {
      id: '/staff/visa'
      path: '/visa'
      fullPath: '/staff/visa'
      preLoaderRoute: typeof StaffVisaRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/translation': {
      id: '/staff/translation'
      path: '/translation'
      fullPath: '/staff/translation'
      preLoaderRoute: typeof StaffTranslationRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/messages': {
      id: '/staff/messages'
      path: '/messages'
      fullPath: '/staff/messages'
      preLoaderRoute: typeof StaffMessagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/consultancy': {
      id: '/staff/consultancy'
      path: '/consultancy'
      fullPath: '/staff/consultancy'
      preLoaderRoute: typeof StaffConsultancyRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/admin': {
      id: '/staff/admin'
      path: '/admin'
      fullPath: '/staff/admin'
      preLoaderRoute: typeof StaffAdminRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/accounting': {
      id: '/staff/accounting'
      path: '/accounting'
      fullPath: '/staff/accounting'
      preLoaderRoute: typeof StaffAccountingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/signup/verify-email': {
      id: '/signup/verify-email'
      path: '/verify-email'
      fullPath: '/signup/verify-email'
      preLoaderRoute: typeof SignupVerifyEmailRouteImport
      parentRoute: typeof SignupRoute
    }
    '/services/visa': {
      id: '/services/visa'
      path: '/services/visa'
      fullPath: '/services/visa'
      preLoaderRoute: typeof ServicesVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/translation': {
      id: '/services/translation'
      path: '/services/translation'
      fullPath: '/services/translation'
      preLoaderRoute: typeof ServicesTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consultancy': {
      id: '/services/consultancy'
      path: '/services/consultancy'
      fullPath: '/services/consultancy'
      preLoaderRoute: typeof ServicesConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accounting': {
      id: '/services/accounting'
      path: '/services/accounting'
      fullPath: '/services/accounting'
      preLoaderRoute: typeof ServicesAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/2fa': {
      id: '/login/2fa'
      path: '/2fa'
      fullPath: '/login/2fa'
      preLoaderRoute: typeof Login2faRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/live/': {
      id: '/translate/live/'
      path: '/'
      fullPath: '/translate/live/'
      preLoaderRoute: typeof TranslateLiveIndexRouteImport
      parentRoute: typeof TranslateLiveRoute
    }
    '/staff/visa/': {
      id: '/staff/visa/'
      path: '/'
      fullPath: '/staff/visa/'
      preLoaderRoute: typeof StaffVisaIndexRouteImport
      parentRoute: typeof StaffVisaRoute
    }
    '/staff/translation/': {
      id: '/staff/translation/'
      path: '/'
      fullPath: '/staff/translation/'
      preLoaderRoute: typeof StaffTranslationIndexRouteImport
      parentRoute: typeof StaffTranslationRoute
    }
    '/staff/consultancy/': {
      id: '/staff/consultancy/'
      path: '/'
      fullPath: '/staff/consultancy/'
      preLoaderRoute: typeof StaffConsultancyIndexRouteImport
      parentRoute: typeof StaffConsultancyRoute
    }
    '/staff/clients/': {
      id: '/staff/clients/'
      path: '/clients'
      fullPath: '/staff/clients/'
      preLoaderRoute: typeof StaffClientsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/claims/': {
      id: '/staff/claims/'
      path: '/claims'
      fullPath: '/staff/claims/'
      preLoaderRoute: typeof StaffClaimsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/accounting/': {
      id: '/staff/accounting/'
      path: '/'
      fullPath: '/staff/accounting/'
      preLoaderRoute: typeof StaffAccountingIndexRouteImport
      parentRoute: typeof StaffAccountingRoute
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services/'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-services/': {
      id: '/dashboard/my-services/'
      path: '/my-services'
      fullPath: '/dashboard/my-services/'
      preLoaderRoute: typeof DashboardMyServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/': {
      id: '/dashboard/claims/'
      path: '/claims'
      fullPath: '/dashboard/claims/'
      preLoaderRoute: typeof DashboardClaimsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/translate/live/session': {
      id: '/translate/live/session'
      path: '/session'
      fullPath: '/translate/live/session'
      preLoaderRoute: typeof TranslateLiveSessionRouteImport
      parentRoute: typeof TranslateLiveRoute
    }
    '/staff/visa/$id': {
      id: '/staff/visa/$id'
      path: '/$id'
      fullPath: '/staff/visa/$id'
      preLoaderRoute: typeof StaffVisaIdRouteImport
      parentRoute: typeof StaffVisaRoute
    }
    '/staff/translation/$id': {
      id: '/staff/translation/$id'
      path: '/$id'
      fullPath: '/staff/translation/$id'
      preLoaderRoute: typeof StaffTranslationIdRouteImport
      parentRoute: typeof StaffTranslationRoute
    }
    '/staff/consultancy/$id': {
      id: '/staff/consultancy/$id'
      path: '/$id'
      fullPath: '/staff/consultancy/$id'
      preLoaderRoute: typeof StaffConsultancyIdRouteImport
      parentRoute: typeof StaffConsultancyRoute
    }
    '/staff/clients/new': {
      id: '/staff/clients/new'
      path: '/clients/new'
      fullPath: '/staff/clients/new'
      preLoaderRoute: typeof StaffClientsNewRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/clients/$id': {
      id: '/staff/clients/$id'
      path: '/clients/$id'
      fullPath: '/staff/clients/$id'
      preLoaderRoute: typeof StaffClientsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/claims/$id': {
      id: '/staff/claims/$id'
      path: '/claims/$id'
      fullPath: '/staff/claims/$id'
      preLoaderRoute: typeof StaffClaimsIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/accounting/$id': {
      id: '/staff/accounting/$id'
      path: '/$id'
      fullPath: '/staff/accounting/$id'
      preLoaderRoute: typeof StaffAccountingIdRouteImport
      parentRoute: typeof StaffAccountingRoute
    }
    '/dashboard/services/$slug': {
      id: '/dashboard/services/$slug'
      path: '/services/$slug'
      fullPath: '/dashboard/services/$slug'
      preLoaderRoute: typeof DashboardServicesSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-services/$id': {
      id: '/dashboard/my-services/$id'
      path: '/my-services/$id'
      fullPath: '/dashboard/my-services/$id'
      preLoaderRoute: typeof DashboardMyServicesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/new': {
      id: '/dashboard/claims/new'
      path: '/claims/new'
      fullPath: '/dashboard/claims/new'
      preLoaderRoute: typeof DashboardClaimsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims/$id': {
      id: '/dashboard/claims/$id'
      path: '/claims/$id'
      fullPath: '/dashboard/claims/$id'
      preLoaderRoute: typeof DashboardClaimsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardClaimsIdRoute: typeof DashboardClaimsIdRoute
  DashboardClaimsNewRoute: typeof DashboardClaimsNewRoute
  DashboardMyServicesIdRoute: typeof DashboardMyServicesIdRoute
  DashboardServicesSlugRoute: typeof DashboardServicesSlugRoute
  DashboardClaimsIndexRoute: typeof DashboardClaimsIndexRoute
  DashboardMyServicesIndexRoute: typeof DashboardMyServicesIndexRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardClaimsIdRoute: DashboardClaimsIdRoute,
  DashboardClaimsNewRoute: DashboardClaimsNewRoute,
  DashboardMyServicesIdRoute: DashboardMyServicesIdRoute,
  DashboardServicesSlugRoute: DashboardServicesSlugRoute,
  DashboardClaimsIndexRoute: DashboardClaimsIndexRoute,
  DashboardMyServicesIndexRoute: DashboardMyServicesIndexRoute,
  DashboardServicesIndexRoute: DashboardServicesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LoginRouteChildren {
  Login2faRoute: typeof Login2faRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  Login2faRoute: Login2faRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupVerifyEmailRoute: typeof SignupVerifyEmailRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupVerifyEmailRoute: SignupVerifyEmailRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface StaffAccountingRouteChildren {
  StaffAccountingIdRoute: typeof StaffAccountingIdRoute
  StaffAccountingIndexRoute: typeof StaffAccountingIndexRoute
}

const StaffAccountingRouteChildren: StaffAccountingRouteChildren = {
  StaffAccountingIdRoute: StaffAccountingIdRoute,
  StaffAccountingIndexRoute: StaffAccountingIndexRoute,
}

const StaffAccountingRouteWithChildren = StaffAccountingRoute._addFileChildren(
  StaffAccountingRouteChildren,
)

interface StaffConsultancyRouteChildren {
  StaffConsultancyIdRoute: typeof StaffConsultancyIdRoute
  StaffConsultancyIndexRoute: typeof StaffConsultancyIndexRoute
}

const StaffConsultancyRouteChildren: StaffConsultancyRouteChildren = {
  StaffConsultancyIdRoute: StaffConsultancyIdRoute,
  StaffConsultancyIndexRoute: StaffConsultancyIndexRoute,
}

const StaffConsultancyRouteWithChildren =
  StaffConsultancyRoute._addFileChildren(StaffConsultancyRouteChildren)

interface StaffTranslationRouteChildren {
  StaffTranslationIdRoute: typeof StaffTranslationIdRoute
  StaffTranslationIndexRoute: typeof StaffTranslationIndexRoute
}

const StaffTranslationRouteChildren: StaffTranslationRouteChildren = {
  StaffTranslationIdRoute: StaffTranslationIdRoute,
  StaffTranslationIndexRoute: StaffTranslationIndexRoute,
}

const StaffTranslationRouteWithChildren =
  StaffTranslationRoute._addFileChildren(StaffTranslationRouteChildren)

interface StaffVisaRouteChildren {
  StaffVisaIdRoute: typeof StaffVisaIdRoute
  StaffVisaIndexRoute: typeof StaffVisaIndexRoute
}

const StaffVisaRouteChildren: StaffVisaRouteChildren = {
  StaffVisaIdRoute: StaffVisaIdRoute,
  StaffVisaIndexRoute: StaffVisaIndexRoute,
}

const StaffVisaRouteWithChildren = StaffVisaRoute._addFileChildren(
  StaffVisaRouteChildren,
)

interface StaffRouteChildren {
  StaffAccountingRoute: typeof StaffAccountingRouteWithChildren
  StaffAdminRoute: typeof StaffAdminRoute
  StaffConsultancyRoute: typeof StaffConsultancyRouteWithChildren
  StaffMessagesRoute: typeof StaffMessagesRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffTranslationRoute: typeof StaffTranslationRouteWithChildren
  StaffVisaRoute: typeof StaffVisaRouteWithChildren
  StaffIndexRoute: typeof StaffIndexRoute
  StaffClaimsIdRoute: typeof StaffClaimsIdRoute
  StaffClientsIdRoute: typeof StaffClientsIdRoute
  StaffClientsNewRoute: typeof StaffClientsNewRoute
  StaffClaimsIndexRoute: typeof StaffClaimsIndexRoute
  StaffClientsIndexRoute: typeof StaffClientsIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAccountingRoute: StaffAccountingRouteWithChildren,
  StaffAdminRoute: StaffAdminRoute,
  StaffConsultancyRoute: StaffConsultancyRouteWithChildren,
  StaffMessagesRoute: StaffMessagesRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffTranslationRoute: StaffTranslationRouteWithChildren,
  StaffVisaRoute: StaffVisaRouteWithChildren,
  StaffIndexRoute: StaffIndexRoute,
  StaffClaimsIdRoute: StaffClaimsIdRoute,
  StaffClientsIdRoute: StaffClientsIdRoute,
  StaffClientsNewRoute: StaffClientsNewRoute,
  StaffClaimsIndexRoute: StaffClaimsIndexRoute,
  StaffClientsIndexRoute: StaffClientsIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface TranslateLiveRouteChildren {
  TranslateLiveSessionRoute: typeof TranslateLiveSessionRoute
  TranslateLiveIndexRoute: typeof TranslateLiveIndexRoute
}

const TranslateLiveRouteChildren: TranslateLiveRouteChildren = {
  TranslateLiveSessionRoute: TranslateLiveSessionRoute,
  TranslateLiveIndexRoute: TranslateLiveIndexRoute,
}

const TranslateLiveRouteWithChildren = TranslateLiveRoute._addFileChildren(
  TranslateLiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevRoute: DevRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  ServicesAccountingRoute: ServicesAccountingRoute,
  ServicesConsultancyRoute: ServicesConsultancyRoute,
  ServicesTranslationRoute: ServicesTranslationRoute,
  ServicesVisaRoute: ServicesVisaRoute,
  TranslateDocumentRoute: TranslateDocumentRoute,
  TranslateHowItWorksRoute: TranslateHowItWorksRoute,
  TranslateLanguagesRoute: TranslateLanguagesRoute,
  TranslateLiveRoute: TranslateLiveRouteWithChildren,
  TranslatePricingRoute: TranslatePricingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TranslateIndexRoute: TranslateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
